server:
  port: 8080
database:
  user: ian
  host: postgres # Change localhost to the PostgreSQL service name
  database: witty
  port: 5432 # Ensure you're using PostgreSQL's default port
  sslmode: disable # Disable SSL mode for local development (adjust if using SSL)
  max_retries: 30
