// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewCustomerInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type NewOrderInput struct {
	CustomerID string `json:"customerId"`
}

type NewOrderItemInput struct {
	OrderID   string  `json:"orderId"`
	ProductID string  `json:"productId"`
	Quantity  int32   `json:"quantity"`
	Price     float64 `json:"price"`
}

type NewProductInput struct {
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

type Query struct {
}
